language: go
matrix:
  include:
    - go: 1.10.x
    - go: tip
  allow_failures:
    - go: tip
dist: trusty
sudo: required
services:
  - docker
addons:
  apt:
    sources:
    - sourceline: ppa:masterminds/glide
    packages:
    - glide
before_install:
  - docker pull carml/go-mxnet:amd64-gpu-latest
  - docker run -d carml/go-mxnet:amd64-gpu-latest /bin/sh -c "ls -l;"
  - docker ps -a
install:
  - glide install --force
  - rm -fr vendor/github.com/Sirupsen
  - find vendor -type f -exec sed -i 's/Sirupsen/sirupsen/g' {} +
  - go build
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)
