jobs:
  - job: CPU
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd dockerfiles
          make docker_build_cpu
          ./push_cpu.sh
  - job: GPU
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd dockerfiles
          make docker_build_gpu
          ./push_gpu.sh
  - job: CPU_Agent
    dependsOn:
      - CPU
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd mxnet-agent/dockerfiles
          make docker_build_cpu
          ./push_cpu.sh
  - job: GPU_Agent
    dependsOn:
      - GPU
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd mxnet-agent/dockerfiles
          make docker_build_gpu
          ./push_gpu.sh
  - job: Update_Microbadger
    dependsOn:
      - CPU
      - GPU
    steps:
      - script: 'curl -X POST https://hooks.microbadger.com/images/carml/mxnet/vdQvZQSNuiSvR9dzwryuJbvyfwc='
  - job: Update_Microbadger_Agent
    dependsOn:
      - CPU_Agent
      - GPU_Agent
    steps:
      - script: 'curl -X POST https://hooks.microbadger.com/images/carml/mxnet-agent/TDLR5KTXvgfzyKLfKBn71v2hmjE='
